#!/usr/bin/env python3
"""Generate SuperCollider UGen wrappers around unmodified Airwindows DSP.

For each curated plugin this emits one translation unit that includes the
plugin's own header, instantiates its class, and calls `processReplacing` from
a UGen's calculation function. The Airwindows sources themselves are compiled
untouched against Scripts/airwindows/vstshim/audioeffectx.h.

One TU per plugin is required, not optional: every Airwindows header declares
`kParamA`, `kNumPrograms`, `kUniqueId` and friends at file scope, so two of
them in the same translation unit collide.

Also writes a JSON manifest (effect names, parameter names, defaults) that the
app reads to build its UI and to randomise chains.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PLUGINS = ROOT / "build/deps/airwindows/plugins/MacVST"
OUT = ROOT / "build/airwindows-gen"
CURATED = Path(__file__).resolve().parent / "curated.txt"

PARAM_LETTERS = "ABCDEFGHIJ"


def curated_names():
    names = []
    for line in CURATED.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            names.append(line)
    return names


def parse_plugin(name):
    """Pull parameter count, names and defaults out of the plugin sources."""
    source = PLUGINS / name / "source"
    header = source / f"{name}.h"
    main = source / f"{name}.cpp"
    proc = source / f"{name}Proc.cpp"
    if not (header.exists() and main.exists() and proc.exists()):
        return None

    header_text = header.read_text(errors="ignore")
    main_text = main.read_text(errors="ignore")

    match = re.search(r"kNumParameters\s*=\s*(\d+)", header_text)
    if not match:
        return None
    count = int(match.group(1))
    if count == 0 or count > len(PARAM_LETTERS):
        return None

    # Scope to getParameterName: getParameterLabel uses the same shape with
    # empty strings for units, and would otherwise overwrite every name.
    name_block = ""
    if "getParameterName" in main_text:
        name_block = main_text.split("getParameterName", 1)[1].split("}", 1)[0]
    labels = dict(re.findall(
        r"case\s+kParam([A-J])\s*:\s*vst_strncpy\s*\(\s*text\s*,\s*\"([^\"]*)\"",
        name_block))
    # Constructor assignments give the designed defaults.
    defaults = {}
    for letter in PARAM_LETTERS[:count]:
        hit = re.search(rf"^\s*{letter}\s*=\s*([0-9.]+)\s*;", main_text, re.M)
        defaults[letter] = float(hit.group(1)) if hit else 0.5

    return {
        "name": name,
        "paramCount": count,
        "paramNames": [labels.get(PARAM_LETTERS[i], PARAM_LETTERS[i]) for i in range(count)],
        "defaults": [defaults[PARAM_LETTERS[i]] for i in range(count)],
    }


WRAPPER = """// Generated by Scripts/airwindows/generate.py — do not edit.
#include "SC_PlugIn.h"
#include "{name}.h"

static InterfaceTable* ft;   // RTAlloc/RTFree expand to (*ft->...)

namespace {{

struct Aw{name} : public Unit {{
    ::{name}* fx;
    float* scratchIn[2];
    float* scratchOut[2];
    int maxFrames;
    float lastParams[{count}];
}};

void Aw{name}_next(Aw{name}* unit, int inNumSamples);

void Aw{name}_Ctor(Aw{name}* unit) {{
    aw_set_pending_sample_rate(SAMPLERATE);
    unit->fx = new ::{name}(nullptr);
    unit->maxFrames = (int)unit->mWorld->mFullRate.mBufLength;
    for (int channel = 0; channel < 2; ++channel) {{
        unit->scratchIn[channel]  = (float*)RTAlloc(unit->mWorld, sizeof(float) * unit->maxFrames);
        unit->scratchOut[channel] = (float*)RTAlloc(unit->mWorld, sizeof(float) * unit->maxFrames);
    }}
    for (int i = 0; i < {count}; ++i) {{
        float value = IN0(2 + i);
        unit->lastParams[i] = value;
        unit->fx->setParameter(i, value);
    }}
    SETCALC(Aw{name}_next);
    Aw{name}_next(unit, 1);
}}

void Aw{name}_Dtor(Aw{name}* unit) {{
    delete unit->fx;
    for (int channel = 0; channel < 2; ++channel) {{
        RTFree(unit->mWorld, unit->scratchIn[channel]);
        RTFree(unit->mWorld, unit->scratchOut[channel]);
    }}
}}

void Aw{name}_next(Aw{name}* unit, int inNumSamples) {{
    // Parameters are control rate; only push changes, since setParameter can
    // recompute coefficients.
    for (int i = 0; i < {count}; ++i) {{
        float value = IN0(2 + i);
        if (value != unit->lastParams[i]) {{
            unit->lastParams[i] = value;
            unit->fx->setParameter(i, value);
        }}
    }}

    const float* left = IN(0);
    const float* right = IN(1);
    float* outLeft = OUT(0);
    float* outRight = OUT(1);

    if (inNumSamples > unit->maxFrames || unit->scratchIn[0] == nullptr) {{
        for (int i = 0; i < inNumSamples; ++i) {{ outLeft[i] = left[i]; outRight[i] = right[i]; }}
        return;
    }}

    // Copy in: SuperCollider may alias input and output buffers, and some of
    // these algorithms keep history that assumes they do not.
    for (int i = 0; i < inNumSamples; ++i) {{
        unit->scratchIn[0][i] = left[i];
        unit->scratchIn[1][i] = right[i];
    }}

    float* inputs[2]  = {{ unit->scratchIn[0],  unit->scratchIn[1] }};
    float* outputs[2] = {{ unit->scratchOut[0], unit->scratchOut[1] }};
    unit->fx->processReplacing(inputs, outputs, (VstInt32)inNumSamples);

    for (int i = 0; i < inNumSamples; ++i) {{
        float l = unit->scratchOut[0][i];
        float r = unit->scratchOut[1][i];
        // A bad parameter combination must never hand NaN to the rest of the
        // graph — that would poison the whole chain silently.
        outLeft[i]  = std::isfinite(l) ? l : 0.f;
        outRight[i] = std::isfinite(r) ? r : 0.f;
    }}
}}

}} // namespace

void aw_register_{name}(InterfaceTable* inTable) {{
    ft = inTable;
    (*ft->fDefineUnit)("Aw{name}", sizeof(Aw{name}),
                       (UnitCtorFunc)&Aw{name}_Ctor,
                       (UnitDtorFunc)&Aw{name}_Dtor, 0);
}}
"""


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for stale in OUT.glob("aw_*.cpp"):
        stale.unlink()

    manifest = []
    missing = []
    for name in curated_names():
        info = parse_plugin(name)
        if info is None:
            missing.append(name)
            continue
        (OUT / f"aw_{name}.cpp").write_text(
            WRAPPER.format(name=name, count=info["paramCount"]))
        manifest.append(info)

    # Registry: one PluginLoad calling every generated registrar.
    externs = "\n".join(f'void aw_register_{i["name"]}(InterfaceTable*);' for i in manifest)
    calls = "\n".join(f'    aw_register_{i["name"]}(inTable);' for i in manifest)
    (OUT / "aw_registry.cpp").write_text(f"""// Generated by Scripts/airwindows/generate.py — do not edit.
#include "SC_PlugIn.h"

static InterfaceTable* ft;

{externs}

PluginLoad(GranolaAirwindows) {{
    ft = inTable;
{calls}
}}
""")

    (OUT / "airwindows-manifest.json").write_text(json.dumps(manifest, indent=1))

    # sclang needs a UGen class per effect to build SynthDefs. All of them go
    # in one file — unlike C++, sclang has no per-file symbol collisions.
    classes = []
    for entry in manifest:
        letters = PARAM_LETTERS[:entry["paramCount"]]
        args = ", ".join(f"{l.lower()}={d}" for l, d in zip(letters, entry["defaults"]))
        passed = ", ".join(l.lower() for l in letters)
        classes.append(
            f'Aw{entry["name"]} : MultiOutUGen {{\n'
            f'\t*ar {{ |left, right, {args}| '
            f'^this.multiNew(\'audio\', left, right, {passed}) }}\n'
            f'\tinit {{ |...theInputs| inputs = theInputs; ^this.initOutputs(2, rate) }}\n'
            f'\tcheckInputs {{ ^this.checkValidInputs }}\n'
            f'}}\n'
        )
    (OUT / "GranolaAirwindows.sc").write_text(
        "// Generated by Scripts/airwindows/generate.py — do not edit.\n"
        "// UGen classes wrapping unmodified Airwindows DSP (MIT, Chris Johnson).\n\n"
        + "\n".join(classes))

    # One SynthDef per effect, so a chain can instantiate any of them at will.
    # Each reads the performance bus and ReplaceOuts to it: series order is
    # simply node order, which is what makes chains collapse cleanly.
    defs = []
    for entry in manifest:
        letters = PARAM_LETTERS[:entry["paramCount"]]
        args = ", ".join(f"{l.lower()} = {d}" for l, d in zip(letters, entry["defaults"]))
        lines = []
        for index, letter in enumerate(letters):
            lines.append(
                f"    p{index} = ({letter.lower()} + "
                f"(lfo * ((lfoTarget - {index}).abs < 0.5))).clip(0, 1);")
        passed = ", ".join(f"p{i}" for i in range(len(letters)))
        body = "\n".join(lines)
        vars_ = ", ".join(["dry", "wet", "env", "m", "lfo",
                           "dryLevel", "wetLevel", "match"]
                          + [f"p{i}" for i in range(len(letters))])
        defs.append(f"""SynthDef(\\awfx_{entry['name']}, {{ |bus = 40, mix = 1.0, gate = 1, fade = 0.04,
    lfoRate = 0.3, lfoDepth = 0.0, lfoTarget = -1, lfoShape = 0,
    autoGain = 1, {args}|
    var {vars_};
    dry = In.ar(bus, 2);
    lfo = Select.kr(lfoShape, [
        SinOsc.kr(lfoRate), LFTri.kr(lfoRate), LFNoise1.kr(lfoRate)
    ]) * lfoDepth;
{body}
    wet = Aw{entry['name']}.ar(dry[0], dry[1], {passed});

    // Automatic gain matching.
    //
    // Many of these algorithms change level far more than they change
    // character — distortions especially — while a few bury the signal under a
    // pillow instead. Both are the same problem: loudness moving when only the
    // sound was meant to. Tracking the dry and wet envelopes and scaling the
    // wet to match keeps a link a transformation rather than a volume ride.
    //
    // The correction is slow (0.4s) so it shapes level rather than pumping.
    // It is deliberately asymmetric: a loud wet signal can be pulled down as
    // far as needed, but a quiet one is only lifted 4x. An effect that removes
    // energy — a notch, a gate — is supposed to; dragging it back to full
    // level would just amplify what it took out, and that compounds badly down
    // a long chain.
    dryLevel = Amplitude.kr((dry[0] + dry[1]) * 0.5, 0.05, 0.25);
    wetLevel = Amplitude.kr((wet[0] + wet[1]) * 0.5, 0.05, 0.25);
    match = Lag.kr((dryLevel / wetLevel.max(0.0001)).clip(0.05, 4), 0.4);
    wet = wet * Select.kr(autoGain, [DC.kr(1), match]);

    // Fading the wet/dry blend rather than the output means adding or removing
    // a link never clicks and never drops the signal.
    env = EnvGen.kr(Env.asr(fade, 1, fade), gate, doneAction: 2);
    m = (mix * env).clip(0, 1);
    ReplaceOut.ar(bus, [
        (dry[0] * (1 - m)) + (wet[0] * m),
        (dry[1] * (1 - m)) + (wet[1] * m)
    ]);
}}).writeDefFile(outDir);""")

    (OUT / "aw-synthdefs.scd").write_text(
        "// Generated by Scripts/airwindows/generate.py — do not edit.\n"
        "(\nvar outDir = thisProcess.argv[0];\n"
        + "\n\n".join(defs)
        + '\n\n"Granola: wrote %s Airwindows synthdefs".format('
        + str(len(defs)) + ').postln;\n0.exit;\n)\n')

    print(f"generated {len(manifest)} UGen wrappers")
    if missing:
        print(f"skipped {len(missing)} (not found or unsuitable): {', '.join(missing)}")
    total = sum(i["paramCount"] for i in manifest)
    print(f"total parameters across repertoire: {total}")
    return 0 if manifest else 1


if __name__ == "__main__":
    sys.exit(main())
