#!/usr/bin/env python3
"""Drop plugins that failed to compile from the registry and manifest.

One awkward plugin should not block the rest of the repertoire, but the
registry must not reference symbols that were never built.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GEN = ROOT / "build/airwindows-gen"

failed = {line.strip() for line in Path(sys.argv[1]).read_text().split() if line.strip()}
if not failed:
    sys.exit(0)

manifest = json.loads((GEN / "airwindows-manifest.json").read_text())
kept = [entry for entry in manifest if entry["name"] not in failed]
(GEN / "airwindows-manifest.json").write_text(json.dumps(kept, indent=1))

for name in failed:
    stale = GEN / f"aw_{name}.cpp"
    if stale.exists():
        stale.unlink()

externs = "\n".join(f'void aw_register_{e["name"]}(InterfaceTable*);' for e in kept)
calls = "\n".join(f'    aw_register_{e["name"]}(inTable);' for e in kept)
(GEN / "aw_registry.cpp").write_text(f"""// Generated by Scripts/airwindows/generate.py — do not edit.
#include "SC_PlugIn.h"

static InterfaceTable* ft;

{externs}

PluginLoad(GranolaAirwindows) {{
    ft = inTable;
{calls}
}}
""")
print(f"    registry pruned to {len(kept)} effects")
